steps:
  - name: node:16 # [A]
    entrypoint: npm
    args: ["install"]
  - name: node:16 # [B]
    entrypoint: npm
    args: ["run", "build"]
    env:
      - "NODE_ENV=production"
  - name: gcr.io/cloud-builders/gsutil # [C]
    args: ["-m", "rsync", "-r", "-c", "-d", "./dist", "gs://react-ssr-test/build"]
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk" # [D]
    entrypoint: "bash"
    args: ["-c", "gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy"]
    timeout: "1600s"
